export enum AuthErrorCode {
  REDIS_UNAVAILABLE = 'REDIS_UNAVAILABLE',
  SESSION_SERVICE_UNAVAILABLE = 'SESSION_SERVICE_UNAVAILABLE',
  OTP_PROVIDER_TIMEOUT = 'OTP_PROVIDER_TIMEOUT',
  OTP_PROVIDER_RATE_LIMITED = 'OTP_PROVIDER_RATE_LIMITED',
  OTP_PROVIDER_UNAVAILABLE = 'OTP_PROVIDER_UNAVAILABLE',
  OTP_PROVIDER_REJECTED = 'OTP_PROVIDER_REJECTED',
}
