/**
 * VyaparNet Shared Enumerations
 *
 * These enums mirror the Prisma schema enums exactly.
 * They are used by both frontend and backend for type safety.
 *
 * Source of truth: VyaparNet_SCHEMA_v4.3_FINAL_FREEZE.md
 * DO NOT modify without updating schema.prisma and vice versa.
 */

export enum Segment {
  TEXTILE = 'TEXTILE',
  SPARE_PARTS = 'SPARE_PARTS',
}

export enum UserRole {
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
  SELLER_MANAGER = 'SELLER_MANAGER',
}

export enum KycStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum QuotationStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  NEGOTIATING = 'NEGOTIATING',
  ACCEPTED_BY_BUYER = 'ACCEPTED_BY_BUYER',
  FINALIZED = 'FINALIZED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CONVERTED_TO_ORDER = 'CONVERTED_TO_ORDER',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  QUOTATION_REQUESTED = 'QUOTATION_REQUESTED',
  PLACED = 'PLACED',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RETURN_INITIATED = 'RETURN_INITIATED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  DISPUTE_OPEN = 'DISPUTE_OPEN',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
}

export enum FulfillmentStatus {
  PENDING_PICKUP = 'PENDING_PICKUP',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  RETURN_PICKED = 'RETURN_PICKED',
  RETURNED = 'RETURNED',
}

export enum ReturnStatus {
  PENDING = 'PENDING',
  APPROVED_FOR_PICKUP = 'APPROVED_FOR_PICKUP',
  PICKED_UP = 'PICKED_UP',
  RECEIVED_AT_QC = 'RECEIVED_AT_QC',
  QC_APPROVED = 'QC_APPROVED',
  QC_REJECTED = 'QC_REJECTED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUNDED = 'REFUNDED',
  REPLACEMENT_SENT = 'REPLACEMENT_SENT',
  CLOSED = 'CLOSED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ESCALATED = 'ESCALATED',
  RESOLVED_BUYER = 'RESOLVED_BUYER',
  RESOLVED_SELLER = 'RESOLVED_SELLER',
  CLOSED = 'CLOSED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED',
  FAILED = 'FAILED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  FULLY_REFUNDED = 'FULLY_REFUNDED',
  DISPUTED = 'DISPUTED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum PaymentMethod {
  ONLINE_UPI = 'ONLINE_UPI',
  ONLINE_CARD = 'ONLINE_CARD',
  NET_BANKING = 'NET_BANKING',
  WALLET = 'WALLET',
  COD = 'COD',
  CREDIT = 'CREDIT',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
}

export enum ReturnReason {
  DAMAGED = 'DAMAGED',
  WRONG_ITEM = 'WRONG_ITEM',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  EXPIRED = 'EXPIRED',
  MISSING_PARTS = 'MISSING_PARTS',
  OTHER = 'OTHER',
}

export enum InventoryMovementType {
  STOCK_ADDED = 'STOCK_ADDED',
  STOCK_REMOVED = 'STOCK_REMOVED',
  RESERVATION_HELD = 'RESERVATION_HELD',
  RESERVATION_RELEASED = 'RESERVATION_RELEASED',
  ORDER_FULFILLED = 'ORDER_FULFILLED',
  RETURN_RECEIVED = 'RETURN_RECEIVED',
  ADJUSTMENT = 'ADJUSTMENT',
  DAMAGED = 'DAMAGED',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
}

export enum ReservationStatus {
  ACTIVE = 'ACTIVE',
  CONSUMED = 'CONSUMED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  RELEASED = 'RELEASED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FAILED_LOGIN = 'FAILED_LOGIN',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
}

export enum EventStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum NotificationType {
  ORDER = 'ORDER',
  PAYMENT = 'PAYMENT',
  INVENTORY = 'INVENTORY',
  MARKETING = 'MARKETING',
  SYSTEM = 'SYSTEM',
  KYC = 'KYC',
  RETURN = 'RETURN',
  DISPUTE = 'DISPUTE',
  PROMOTION = 'PROMOTION',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  AUDIO = 'AUDIO',
  PDF = 'PDF',
  THREED_MODEL = 'THREED_MODEL',
}

export enum CartStatus {
  ACTIVE = 'ACTIVE',
  CHECKED_OUT = 'CHECKED_OUT',
  ABANDONED = 'ABANDONED',
  EXPIRED = 'EXPIRED',
}

export enum SupportTicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING = 'WAITING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum SupportTicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum FieldVisitStatus {
  SCHEDULED = 'SCHEDULED',
  IN_TRANSIT = 'IN_TRANSIT',
  ARRIVED = 'ARRIVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum FieldVisitType {
  DELIVERY_VERIFICATION = 'DELIVERY_VERIFICATION',
  QC_INSPECTION = 'QC_INSPECTION',
  ADDRESS_VERIFICATION = 'ADDRESS_VERIFICATION',
}

export enum SystemActorType {
  USER = 'USER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
  CRON = 'CRON',
  WORKFLOW = 'WORKFLOW',
  SELLER = 'SELLER',   // Added Sprint 5: seller-initiated status transitions (INV-S5-22)
  BUYER = 'BUYER',     // Added Sprint 5: buyer-initiated cancellations (INV-S5-22)
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  TRANSFERRED = 'TRANSFERRED',
  FAILED = 'FAILED',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FLAT = 'FLAT',
}

export enum BuyerLedgerType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum MediaClass {
  PRODUCT_IMAGE = 'PRODUCT_IMAGE',
  COMPLIANCE_DOCUMENT = 'COMPLIANCE_DOCUMENT',
  SWATCH = 'SWATCH',
  SPEC_SHEET = 'SPEC_SHEET',
  CAD_FILE = 'CAD_FILE',
}

export enum ApprovalPolicyType {
  AUTO_APPROVE = 'AUTO_APPROVE',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  DOCUMENT_REQUIRED = 'DOCUMENT_REQUIRED',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
}
